upstream otel_grpc {
    least_conn;
    server otel-collector:4317;
    # Docker Compose DNS resolves to all replica IPs

    keepalive 64;
    keepalive_requests 10000;
    keepalive_time 1h;
}

server {
    listen 4317 http2;
    client_max_body_size 64m;

    # Resolve replica IPs dynamically (Docker embedded DNS)
    resolver 127.0.0.11 valid=5s ipv6=off;

    location / {
        grpc_pass grpc://otel_grpc;
        grpc_next_upstream error timeout;
        grpc_connect_timeout 5s;
        grpc_read_timeout 300s;
        grpc_send_timeout 300s;

        grpc_set_header Connection "";
    }
}
