receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        max_recv_msg_size_mib: 64
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_size: 100000
    timeout: 200ms
    send_batch_max_size: 200000
  memory_limiter:
    check_interval: 1s
    limit_mib: 2048
    spike_limit_mib: 768

exporters:
  awss3/traces:
    s3uploader:
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      s3_force_path_style: true
      s3_bucket: ${S3_BUCKET}
      s3_prefix: ${S3_PREFIX}/traces
      file_prefix: otlp_
    marshaler: otlp_json

  awss3/metrics:
    s3uploader:
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      s3_force_path_style: true
      s3_bucket: ${S3_BUCKET}
      s3_prefix: ${S3_PREFIX}/metrics
      file_prefix: otlp_
    marshaler: otlp_json

  awss3/logs:
    s3uploader:
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      s3_force_path_style: true
      s3_bucket: ${S3_BUCKET}
      s3_prefix: ${S3_PREFIX}/logs
      file_prefix: otlp_
    marshaler: otlp_json

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [awss3/traces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [awss3/metrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [awss3/logs]
